site_name: KeppyLab
site_url: https://www.keppylab.com
theme:
  name: material
  icon:
    logo: octicons/north-star-24 
  favicon: assets/KeppyLab.png
  palette:
    primary: amber
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy
  custom_dir: overrides
nav:
  - Home:
    - About the Lab: 'index.md'
    - MCPM: 'mcpm.md'
    - 'Writings & Research': "blog/index.md"
    - Contact: 'contact.md'
  - MCPM: 'mcpm.md'
  - 'Writings & Research':
    - "blog/index.md"
  - Contact:
    - Connect with Me: 'contact.md'
plugins:
    - blog
    - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/keppy/KeppyLab
extra:
  social:
    - icon: octicons/mail-16
      link: mailto:james@keppylab.com
    - icon: fontawesome/brands/github
      link: https://www.github.com/keppy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/james-dominguez-5b342b226/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/keppylab_ai
    - icon: fontawesome/brands/hacker-news
      link: https://news.ycombinator.com/user?id=keppy
copyright: Copyright &copy; 2024 James Dominguez
